---
title: Основы обработки данных с помощью R
author: Tashlanov Vladimir
format:
  md:
    output-file: README.md
---
# Основы обработки данных с помощью R

## Цель работы

1. Развить практические навыки использования языка программирования R для обработки данных 
2. Закрепить знания базовых типов данных языка R 
3. Развить пркатические навыки использования функций обработки данных пакета dplyr – функции select(), filter(), mutate(), arrange(), group_by()
## Исходные данные

1. Программное обеспечение Windows 10
2. Rstudio Desktop
3. Интерпретатор языка R 4.4.1
## План

1. Установить программный пакет dplyr
2. Проанализировать набор данных
3. Ответить на вопросы
## Шаги

1. Установка dplyr
```
install.packages("dplyr")
```
2. Выполнение заданий:
* Сколько строк в датафрейме?
```
> starwars %>% nrow()
[1] 87
```
* Сколько столбцов в датафрейме? 
```
> starwars %>% ncol()
[1] 14
```
* Просмотр примернового вида датафрейма
```
> starwars %>% glimpse()
Rows: 87
Columns: 14
$ name       <chr> "Luke Skywalker", "C-3PO", "R2-D2", "Darth …
$ height     <int> 172, 167, 96, 202, 150, 178, 165, 97, 183, …
$ mass       <dbl> 77.0, 75.0, 32.0, 136.0, 49.0, 120.0, 75.0,…
$ hair_color <chr> "blond", NA, NA, "none", "brown", "brown, g…
$ skin_color <chr> "fair", "gold", "white, blue", "white", "li…
$ eye_color  <chr> "blue", "yellow", "red", "yellow", "brown",…
$ birth_year <dbl> 19.0, 112.0, 33.0, 41.9, 19.0, 52.0, 47.0, …
$ sex        <chr> "male", "none", "none", "male", "female", "…
$ gender     <chr> "masculine", "masculine", "masculine", "mas…
$ homeworld  <chr> "Tatooine", "Tatooine", "Naboo", "Tatooine"…
$ species    <chr> "Human", "Droid", "Droid", "Human", "Human"…
$ films      <list> <"A New Hope", "The Empire Strikes Back", …
$ vehicles   <list> <"Snowspeeder", "Imperial Speeder Bike">, …
$ starships  <list> <"X-wing", "Imperial shuttle">, <>, <>, "T…
```
* Количество уникальные расы персонажей
```
> length(unique(starwars$species))  
[1] 38
```
* Самый высокий персонаж
```
> starwars %>% arrange(desc(height)) %>% slice_head(n = 1)
# A tibble: 1 × 14
  name   height  mass hair_color skin_color eye_color birth_year
  <chr>   <int> <dbl> <chr>      <chr>      <chr>          <dbl>
1 Yarae…    264    NA none       white      yellow            NA
```
* Все персонажи ниже 170
```
> starwars %>% filter(!is.na(height) & height < 170) %>% select(name,height)
# A tibble: 22 × 2
   name                  height
   <chr>                  <int>
 1 C-3PO                    167 2 R2-D2                     96 3 Leia Organa              150 4 Beru Whitesun Lars       165 5 R5-D4                     97 6 Yoda                      66 7 Mon Mothma               150 8 Wicket Systri Warrick     88 9 Nien Nunb                160
10 Watto                    137
```
* Индекс массы тела всех персонажей
```
> starwars %>% filter(!is.na(mass) & !is.na(height)) %>% mutate(bmi = mass / (height/100)^2) %>% select(name,bmi)
# A tibble: 59 × 2
   name                 bmi
   <chr>              <dbl>
 1 Luke Skywalker      26.0
 2 C-3PO               26.9
 3 R2-D2               34.7
 4 Darth Vader         33.3
 5 Leia Organa         21.8
 6 Owen Lars           37.9
 7 Beru Whitesun Lars  27.5
 8 R5-D4               34.0
 9 Biggs Darklighter   25.1
10 Obi-Wan Kenobi      23.2
```
* 10 самых вытянутых персонажей. Вытянутость = масса / рост
```
> starwars %>% filter(!is.na(mass) & !is.na(height)) %>% mutate(stretch = mass / height) %>% arrange(desc(stretch)) %>% slice(1:10) %>% select(name,stretch)
# A tibble: 10 × 2
   name                  stretch
   <chr>                   <dbl>
 1 Jabba Desilijic Tiure   7.76 
 2 Grievous                0.736
 3 IG-88                   0.7  
 4 Owen Lars               0.674
 5 Darth Vader             0.673
 6 Jek Tono Porkins        0.611
 7 Bossk                   0.595
 8 Tarfful                 0.581
 9 Dexter Jettster         0.515
10 Chewbacca               0.491
```
* Средний возраст персонажей каждой расы вселенной Звездных войн
```
> starwars <- starwars %>%  mutate(age = 2024 - birth_year)
> average_age <- starwars %>% group_by(species) %>% summarise(average_age = mean(age, na.rm = TRUE))
> average_age
# A tibble: 38 × 2
   species   average_age
   <chr>           <dbl>
 1 Aleena           NaN 
 2 Besalisk         NaN 
 3 Cerean          1932 
 4 Chagrian         NaN 
 5 Clawdite         NaN 
 6 Droid           1971.
 7 Dug              NaN 
 8 Ewok            2016 
 9 Geonosian        NaN 
10 Gungan          1972
```
* Самый распространенный цвет глаз
```
> eye_color <- starwars %>% group_by(eye_color) %>% summarize(count = n()) %>% arrange(desc(count)) %>% slice_head(n = 1)
> eye_color
# A tibble: 1 × 2
  eye_color count
  <chr>     <int>
1 brown        21
```
* Средняя длина имени в каждой расе вселенной Звездных войн
```
> average_name_length <- starwars %>% mutate(name_length = nchar(name)) %>% group_by(species) %>%   summarize(avg_length = mean(name_length, na.rm = TRUE))
> average_name_length
# A tibble: 38 × 2
   species   avg_length
   <chr>          <dbl>
 1 Aleena         12   
 2 Besalisk       15   
 3 Cerean         12   
 4 Chagrian       10   
 5 Clawdite       10   
 6 Droid           4.83
 7 Dug             7   
 8 Ewok           21   
 9 Geonosian      17   
10 Gungan         11.7
```
## Оценка результата

В результате работы были выполнены задания по набору данных starwars.

## Вывод

Были изучены функции из библиотеки dplyr и выполнены поставленные задачи.